Models/ErrorViewModel.cs
using System;

namespace MVC_SinhVien.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using MVC_SinhVien.Data;
using System;
using System.Linq;

namespace MVC_SinhVien.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new SinhVienContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<SinhVienContext>>()))
            {
                // Look for any movies.
                if (context.SinhVien.Any())
                {
                    return;
                }

                context.SinhVien.AddRange(
                    new SinhVien
                    {
                        Id = 01,
                        Name = "Triều",
                        DiaChi = "Quận 7",
                        GioiTinh = "Nam ",
                    },

                    new SinhVien
                    {
                        Id=02,
                        Name = "Oanh",
                        DiaChi = "Quận 9",
                        GioiTinh = "Nữ",
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
namespace MVC_SinhVien.Models
{
    public class SinhVien
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string DiaChi { get; set; }
        [Required]
        public string GioiTinh { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_SinhVien.Models;

namespace MVC_SinhVien.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SinhViensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_SinhVien.Data;
using MVC_SinhVien.Models;

namespace MVC_SinhVien.Controllers
{
    public class SinhViensController : Controller
    {
        private readonly SinhVienContext _context;

        public SinhViensController(SinhVienContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString, string sortSinhVien)
        {
            var sinhvien = from sv in _context.SinhVien
                           select sv;
            if (!String.IsNullOrEmpty(searchString))
            {
                sinhvien = sinhvien.Where(sv => sv.Name.Contains(searchString));
            }

            ViewData["NameSort"] = String.IsNullOrEmpty(sortSinhVien) ? "name_desc" : "";
            switch (sortSinhVien)
            {
                case "name_desc":
                    sinhvien = sinhvien.OrderBy(sv => sv.Name);
                    break;
                default:
                    sinhvien = sinhvien.OrderBy(sv => sv.Id);
                    break;
            }
            return View(await sinhvien.AsNoTracking().ToListAsync());

        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = await _context.SinhVien
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sinhVien == null)
            {
                return NotFound();
            }

            return View(sinhVien);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DiaChi,GioiTinh")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sinhVien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sinhVien);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = await _context.SinhVien.FindAsync(id);
            if (sinhVien == null)
            {
                return NotFound();
            }
            return View(sinhVien);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DiaChi,GioiTinh")] SinhVien sinhVien)
        {
            if (id != sinhVien.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sinhVien);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SinhVienExists(sinhVien.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sinhVien);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = await _context.SinhVien
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sinhVien == null)
            {
                return NotFound();
            }

            return View(sinhVien);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sinhVien = await _context.SinhVien.FindAsync(id);
            _context.SinhVien.Remove(sinhVien);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SinhVienExists(int id)
        {
            return _context.SinhVien.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_SinhVien</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SinhViens">MVC_SinhVien</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MVC_SinhVien - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/SinhViens/Create.cshtml
@model MVC_SinhVien.Models.SinhVien

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SinhVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SinhViens/Delete.cshtml
@model MVC_SinhVien.Models.SinhVien

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SinhViens/Details.cshtml
@model MVC_SinhVien.Models.SinhVien

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/SinhViens/Edit.cshtml
@model MVC_SinhVien.Models.SinhVien

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SinhVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SinhViens/Index.cshtml
@model IEnumerable<MVC_SinhVien.Models.SinhVien>;


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="SinhViens" asp-action="Index">
    <p>
        Tìm Kiếm <input type="text" name="SearchString">
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSort"]"> Name</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)

            </th>
         
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
           

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>